#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 82254f5f-da4a-41e4-a131-e158823ca79c
# Source File: C:\Users\mdl27\Desktop\CoralSea Project Source Code\Coral Sea Backup Warning\Coral Sea Backup Warning.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
/gEAAB+LCAAAAAAABACNkV1LwzAUhu8H+w8h97VL12KFNBfrnHjhB9vQSzm2pyOaJiFtxf17U9tJ
hyDe5UnO+7wk4VsszAe64xpaEPMZIfzRmTcs2m/w+ISukUYLxsPTcjzZSIW3a5FGURJXSRWUEEMQ
M4wDYEsWIEvSNFoWcHlV8HAcHqNjx/5oUSx4OMWJvBlhRLLFCh3qAu+hxoxSsuqkKjO6oGLXgms7
e2GbZuj6O5qDUsEdSL0xrn6xTTV1nfa9rPq37EaZV1BexSYqkpu6Bl1ef7ao+6fL6N51SMUw3fgG
dtYwwHDvn2cZ6MHJg9Sg+oG+V+TGgSI7BLKC4r2z5BmclvrgpdYHefgrMZ/x8Oy/vwBYsa4b/gEA
AA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.93
     Generated on:       9/30/2015 12:18
     Generated by:       bmo6
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2015
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
SwQAAB+LCAAAAAAABAC9lEtLAzEQgO+C/yH0vOzD7boWsgtS6UXQ4kr1mk1nS2geZZK07L93W0sV
PYiFhlwyEzIfH8MMfQFutoD9A3OMDBcrjK5GN6P6+ooQ+oxiJTSTMyHhiSmoG8fQ+U28sZYmv14P
f+6tBdVKAfYQf2X6WlluUIo2IosjaRyn+xORqZfOI1QavEMmIzL3Qw3+CP2rWYOu2rJkBS9us0k+
hvRuQpNT1Z+UprcOVAhG/Cb00uxsPDOobBDivk9hQMh2Qq/OYaV5V3Rll2XLImU5+5v1rmQYJ4HA
ncG+AdwKDme17N92U4MQRO9oNUczqF3A7RR+zjZNvi+P+gNBqg7+SwQAAA==#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Call-MainForm_psf) -eq "OK")
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
Y8IAAB+LCAAAAAAABADtfWtzqkrT6PdU5T+k8pVVu0VU4NRe61RiYrxL4jV+eQsUvCEoIiq//swM
qIDczErWXu+pzPNU9hqBpqenp6dv0/z7Jo90SzYOT6Ip3qF/bGa69vM+e//r9ubu7t+WMZvMNFEt
zVS5KS7lXw1xppV0Y/nPaqP8CxeXnYekuTwy78zDSv553z5sTHn5T3+mjfXd5h/8rPP3x13YpR93
PReH3D8Z/L8fd8Wtam4N+acmb01DVH/cCVtJnY1q8qGjL2Ttp8SyYn6UL9A8k5MzHH9/pyFUft4f
Ub2/G01n6thAt94Xdc00dHXjDA/hKhj6SjbMg/tMUZ3Jmtme2fL9r3wOvZxmM//C8aaIhyojXTsC
RFcfEUWMw6+Hh4fHh4fXh2f0F7fKw6OO//k2QX+KDxPyY/HhYY1/rOWe0d9dw7l18lCbqOjxfukV
QUBXbm8cCA/6K3oO5jp6kgB4dX9H7dn9L/7x9SG8PQFutzfwie0/gEaBxUK+ZaiQpw4a8AV1YICy
mgIU1uzaAoujrsSNB4WB5ZoS4UAP6xan94oa1HrdNRzUXs3t3940l88MsMrLVnBwSMJRLRwGYPPL
V4Hnl2UWxtVHGg5mvy5w9u3NoNMBOT9kgdn2FYHLDDoDsEZrPg4sQw0UBGGAIQyeEBqWUUAYlW5v
TOC0XnGOsV6h8agMwDhnMlDtNZZg00vBgiwlSOFg8+2VqqBRtjWo0/oO023A8Aq139XLUCu9rhw6
wDDX1CDDWx04jLs1wXljNM68NR88Ibo5lOSHDcF5OEfN58CWixuFOuyMOnBKZw98eZhRTmNYQ369
XVqXMJ05Hb3n9+7cWP3OE/DCIANUZ5UXKHpfH4A5atMA5QynwFt2XIYq/ao791OisTIC0M50mJlL
wZltTIe0VOge5rBrMI+R/LYoyB2o9xZbsJvjpgAFNG9gcn3GhUAon2sNJsCzc8bi1O5BQri9Zk20
ZOd5SoiAa7EUFF5oXeGoYYcFKbffQXZZFhVu3ZtZ0FB3B8gW6hLw29ubWRagqXIMcFJ7H0LZQCMc
vGLXOtjVcQP8awLNqbsqhOUIgBOEHSSuiWAzOZkBo37YILrltrMZUK1VBRy6gMTwyTiGtr9RvhHZ
u8OSHBHr4UE4//I7fQTtMHF2jONm4NkHJo8R24C7D3zNSL+hfUP726ExFCiw4+AJaNPuA2e0D0hY
0g3bkcGgFW5vKOVqefYpuIEj1Sl2z1qUthUV6A9MEew3tG84u+PtTaX0MIVD6a1icUbvYIPw0uCB
ab+OBXjJcBLSCqzCF+HmazYHApU/1DV4fVEf4FB9Q7jBhfa06rWNyz7ZT5udqsCr06WENgBl9pm4
+VqOUjDd5rVWAw7DXjUtjqF9smPnbm+GTxrsG/AMgObrg3vVsZ1HSoHNQm49nVkeXcijbTmazLRX
U8JxxNfxvnDxRBc9QQ9sCamPQu1juPkbHjXSjSSkXfVel84bqedlruPoRrwgZQA6WV4Aw8gizack
NRCOtzcnrOkS3VWgRjcM7xOob0E7yzfcMVBiB72rBZtrcLtshZaNNJnpvKV45t7OL9FWmqcs7QSN
QbYAzyyYuaM5+zgWadac8rr3guWE5g792G0/uTMx7FSxRcIYGJrCxmrzMXTtG1UJKnRlccTAoVsr
W+EAng6cqxGSlZ7NViWv5uzBebuRfZJgw1I2HN7atzdVH//sh3UFlHzzemwxv6KRZqZm27UgPDgw
709z79wRSouVnu7OrQcDzNGUvZM6vjmljC0y6IIzQeiSX5rLFDL6gkOmebkM9dLIvFjZdk9uKmCw
2+Ni1gqUwuvT/vxkPxC99/wEW3/YeFd+oU+vFG7ZPSh+6xFRZaDxSlBSpOBebiDsFW7abdcv5rbZ
y2URgcyCdYTmGMbYluPn034HhpXeArLt0lDgl1jGHsZC1Qt8VW8vHI69kCUI2rCL9ESB4RJx9DRz
U8vifaASgEjoRg/mEhRke3UNxHOjFmatA1W1oWH5djF342achRsOMbdjyX6qPs9DucFCBlBLuwpL
z5wW2pmVcMEN7txlkH0q5ZJsnACHcPO3gxDHDdqmoLhjI7wwM5YCv571LRBzqoGgZbdVEXhzhk1P
s+PbB6K5gX8YLi55IZl781sDrdv8e/1yP0W8MEBmMHs0xfOIeyNlA7HbD7t63QObUk1xQLjhQqvI
9kuIe62r9TcOFBu65eabu1ueMEAjtceTluCIT6ddygbfPsEKj6bXai9sC2s42vUeOsy6bQH0emvy
MS2CWtzemIUOBDn4o/vEeU43XDGDd4rTPoEpaz/KDQXUwnaQCrsQDiF6LV8UM4LHo8I/it0yUIqR
d+8i/jh5+JaHQ69TdXE80m3cqwlQzozmXrgV3C/TzxN3VGTVzcV+M4quKTUHrItz9dYOS/GDO9fE
CUfl9pIG20Y/D+wc8dtWoWQjz0KjpO+9lO0MSi1gO0VT8T4xQH2+LnUtB2ImbyMlx+YV4RrcopqC
dJh8dq/h/XiG6eZwKFnZhC7Oqjl7noKeTud66P0UWlloCWTlp+Fv4eg2r96LFmuhzSCJue63rctV
lUI3x/sC0YzJOnvL8hXgFZm+3jMVwC22Eb8l35XVjquv+WWHX3/z/KJ2ZxLSQyYm5IqjiQJbTk6P
4+9aRkoOKaaP9qhMfNJYf6vqr8Dt+3OkG/VGWyK1AUnpzsCRiPniciHAOMczkKTVfrFdT+aSWEmU
bbEC0ue2ZcejDALNubKDrNs/j9s3tG9ofw20KO/vsTlRxc9qvw1Nx39IBPTFhfaI46OkVR7UqMec
lR7c45PtLHKHsy+cIYT3AxCP0OLfmbbvxS30jqtwRNB8d5AW3P3Cr4fcj3Hz4BQhU9O2WLoFRxVs
F2PAI42iwxXNHZNnFqL5KZyOIddPdIu8I5k7zu0D/BYcg4dKLt2iR5HuDV7ckkaZjoMtwr3p6JQK
oo9uqeL1F33PmvDyW/COmDWSrIeE3pFqJnx0C8UpfNTRqyyIW8IoQtoFBnHr9Pp1G7pOY7ghiJN/
TIGRRo8yZuWf+z5+y1OKBhx0bMfiBZNr4dSRJxOgbHOK66nCltpH94VgP3buQ9dpOMSkfQNi5Btp
DNVRgBUeNkDVtJwBoj40gC5luhZfGz1b0GYeG0Dn+YHF8+qAQdD0+ssUOKtzwA8LSiocomRyBL99
cJ8IroXovYmgz1q1LfCLSXYAzVKORpZev2adozCnuEzQqvbEafJiHZmU0vMcVDHbA+ppmRNcmyYw
6s/SLSP2haTmoSOOmcAoN7bhPfc2h0Opc3tTsVw/5cnLE+5riOkTKr0schL2v/FrAajVVtSQSa/Q
sSs9of2WfAve79KN4IQjEmgU/YMGFfp5cR418QmmijQG4gvhsUepM7XRqlqtXe9G5BgC+0LoKELp
GAoxVg+xuC3AvPaCo3YDhCPxwMTNNfaHaI6v9KB2T9zh7RdP/V7g+qlf6VVmkDF3tzcdATpZ7HI9
y9QPa4Sp9TdPf5DlFaqmVwy0rl811wtEcERzSrAmninPKI7901x3A2skQBXnfi/dghCb7arA16WM
DTTPHF20sVKf2AvBufTMfpI2dn4D9jAjaPmiusDybDZ3PcbNcVPhh7JqQJ/ZS0CbXB94SSlZ3r4o
0xY0epuDP9/SoQOOJvHNUZdFT9CjCAgjpWfDa3b67EJYdGcD6GlTdAkWTPp9IZXuFKeH0GO7B4e3
fvW4BvDMkOiBE8v0hMVPQW8MrZ7hLEoz1wraOTJ0gOcRFR5fKwq/nS1ZN0fFD8Htk9jm7U2fWY28
HFhRG3Ngsu+KglQSwb4cVShHO80daXpuIPHT7mDadn33Hv4skfwQ/nVEH739QX7DuhGOBtQRzpW5
T4J69oVeW4FNvbALrFMCAe9FiBdrAKVM7v20RrBXG++v+/xrGeAl07iME6aws1JzC7W+vbFqBpTV
B+UyWwPThW9IGaQRWk/bCwhUR88LfHGYEU7xLc++cN5PV9i7j3SnibsDe3DQkP5JieuVAU6ukEei
un5yIiukSc9yFa/rLLUwf4inkTswDnxrtGChWqqo/r0Mj4FQoSR2JTcBw6f3Ygg8M2cUjn2f2944
X5AbSKbrsrZ9xwEUELw4znFUUaDeVtWyN0IW3EkW3fYAdiP7MbWdFc4dYX0nYmv22+xRZp+k+nFf
IBkjZLbzrfniyECnUfDGJGtx+fcnw08FsjuedStnX1iI/TcnL8tLByXPA1XVdM2bURKEMO7sWRiv
qtnTnCbZUTE285lubn5IfrtZnjLUX9enNVE03D6JNlHDJ3AzwQJ0dKhQeO+c41nqeVUFtIJ5oS24
VPA0nFFMPS/1zpEfux495MxPBMfXpYoD3hkuxnoMG3VwPz3fwcHAhuz6RTznnq0uY0VHKiApL0vT
gP8tQAdPhCzI0QSihwpHe4FgSXLai8v3emBdBnRxchZgs0OI9087RoRdH7omQrmF5AJl9vtOIA59
zie/oAPZ7YJUsKZZ4J/F7gDqJX0DB1qqK2iVHRio9zYmlm/kl/3gqY7sqFnvck0QKjyouafLPK+A
5o1wU98NYAePpnLNmgjdN1z5Rng887Z+E7x0ILLBXRNE2+/giCumArMV5Ms3GizOmoA1KxtOfhs1
3xQE0NnW/KLvkfIenPxU8OTVFEMsEMxfOMMJKTFgRcfYIOAPiW5MqzwCm14IVnhWApJOJyrgfMsj
HZJsv2SvUFC+XXBDN7DTdL35lZA/bDXByRc5Qkvy0URzCyPXx5B51F6VY36vz2Y+SenzmgjnhtC+
T3/ztFC/ZciaUPyy5ayHXNAhlefTTxW/fUqyhS7WhE9rCFkTl/4Qg6Vce5SFOr52wBQJ6/OKREdR
4fbmQjaErIkq3dUv18Tl3Af9b9GNaISZ/KEDSM89S4ZeIB/JR4eOnxtwcyRkWewqzkkm+1FqCNyu
bz9Bo7Q59jN9G+dbqutlP6WEDPpwHJzUEZKPUtGEa2OUEMHBxKZhas3bmxGESMh2yD6B9ssLTTqw
W4bkDYbvl0FuuNwtHfvUq4sjCI3e7oBM0zGdNhoQEZfxjAJ7M5w8Qr9nQAnbLc+6U0APidIagv63
CN0Jz2lQe5p6fDSvx5khHrv2C42sr3mBEsJl8FEPSbayfX1eEDPA7QZPx7N4ju7kzauJ0aTPVPBq
0t1aQA929RC/Ju3B6UKTDnquHE36jYHJal38sIc2ys46/cLLCs1Cpfc8u+TocLvqTEfHqrq9OdtV
08CpjKlrVxleu8rT8IlEv1UV1N8IBLV3kODAS3XfqEJH6e+n8b+RBwoHw0JUaMx80ql0si6bUgbz
m8fKPtMhxMoOlQx+G9sn34wCZVFjY8i6Vva064dQfatYvDXP4qSkOROmlwTj9dd7olA78EIdxPfp
Csu3R3wqyIMD6gv8QFYVb36lp2G/E1+SniW/xyUo3xa9ogQbgzpc4kQ8LszOUPwel/Yxj3A1ROJA
vL3JNY3L14fObTIVQlcWuYPYC/Zw2rQ8PmjbnAsCdbCMuhOdcnyC5LwD7iNoZIIo3SxoTia1I2M9
ez4+bcXvZ0zZOTMWgOD2B8xYwZnzlceFlyOrKtIS8svN0rqI5ASpcNG/iAPG6rU+7iCn4blVf3Zc
E/nh7U0dkGxYDOBtuX+BzHDzZvEvePZPfWxXLQZOZuLFeS2y03Dvto3vL+O8wRAIFl+WunNovTzk
XAgkEiTq07UbDQ1ycNScfsjOcq5791OsETr54jV1svF6Rj1+dI8n4eJ0VdfVewM+l1BPfC/MM0+4
Zz7pC0QmJ+wLMdkbEftpDP8E+lkeJDDqW2wzy8hCnndnnbNuFdhPg96JoHxL7hO6Ea2gQr+6Z1FI
6nxcnk1kP9LOitknou0wfF7GZoE1KluLr0gLDV66GdHPHa8rn7YVjEadqYT9SJEnCrGvlZt1D3WY
icUaUJp5PKURpSFeqznE7BMR0ELpSM43zGvtJtjNaVPgRliTqdINn7fNd34hJlZJ6DLpFpGWQD8s
gD4UB4qTogsC0qs+kOfgaXF0S7SJAxBC78d/8L6AI6xUc/XOwlvffMHqTEM4SvXXkPj9uV+jkVVk
r+Yt4FfTLKabtVlSblWKpJlI4uAoDkmSkBEtFb85lhneKPnye0ahNtu1DYt1vw1MtqcofG5RnoM8
LOE4YE4eT4GabMQnsBoyB5S1PR1ETIgnhOCWFOFPP+pLOyumJV8/62/OmWtStYLmYeBmKZDaHSc/
USzOl3lcSTglZC347KzwJ5K8Z543psxTDe37RxnvJw/v/5Z8i95PQ+/3QbtiZwnn6JT6W/CNyX7L
VBDjOTiS32LWZbi25bXrYyBG96Nx87ekTJ0Ir2NMnkOwH71mfOs0VPdOtwYCLYRuSdwR2i75Laal
1DGT8smTLBJ/PxK3K+h2qfeGjio1TsdHw88ZJWoRoc3Hb+n1jsj7w/J7U0GMpdv5l9NZClxbiDSn
1hBpAsRev71JuuOa67c3vwvBex1B+00I3uvnEy6fgeMR2u+P0qkr9VmjrD0QaLge4fH4zatbrRD/
8/SvQIuqUAb/P52o+ob2De0b2je0b2jf0L6hfUP7hvYN7Rva/7/QSJ1QFgQLOKG+A74j3d7QAq4a
poFuvMwg31dVheqthgNQxX4P8oWtZlG2ZQiQGc/fgLK3rOBACDvr+feM9M9BI35xUp+csqw1ruRt
7iGz33Zwpn/Hhjq92JHTLhYndt4sKC1277AfNl4EJ0P9WI9rqrQEviJm5jB8f1xCPmtpCrwz/NyZ
q79gpH8CGuEnUjfq0BQqkOtPphb/JHaPWVqkEh+pMYb7OD+ERPDDq5+WThnppDaRk9tzhtDMPuSA
eXkbKTjvBseznPPMZJV8+Uj/A2ikfv50mC1hfhurLYHrt/cKpsssqspTmn5U/JSclup1HiWo0RsD
mNrryIJKZjMHJ4foC0f6B6GRAPDjgSvDm9Z8cSoAO1HiYDZlWrpd23ei8bc3mKdb/fcCFOTsCpwT
+p850o+3K6GRbDZmxyqUZFQtqPcyJlq37Yp1yif/FLpF1DGLqe5MOHrcw9mQQ/kRqCc1F/hyxl/O
vU6eIP6qRHGp16Hae9fCqpt+It1S9j15+DjHbr8XyhY/UbJlyPBG5/Ls0x+mW5pGqrdRj8t3tPJp
nJXlrTUZft45NOvqCrpNMd1Cz2B78lYvr5M8QpLvmxVx2cM+M5bi41lfSbfEhvNLqPbtzWqFOJZ+
113KOqOi3zfuqDw1KIKVHknfyWHBJ598edExdQmM3syG8FqT/v7tja/65OkUpENp6V01gZLW+ZTV
UP/cLODENafoYJVeaGQn8XJLdluWBErb1uawZrcGFLbs7c0a17AuWKdffP08tdPcfMzg6T0PnYed
vQbLQnaEcEMQDCEG4qlvgzJ8o8B+FBvuuSJyimNPv5Ytqrta4XMf5Ks5f4BuSY1ose+Mic9d5ovu
OXGfVkqyuZ/E5w5sN2IhMbBLUp2pivY+x6dd9pjfovU1Z2Uf0NwhHMbzxNDx7U22yb4Dbeb7Lk97
NBc311FHZshTbeer3PL5dEsJjZzIH+n8gWgFEdp/qbsZQHb2JApnIzUMGtH2if7WWD4cYM+/VS5q
NV9IBhWf2L+9QTwsHfPoQxvOC8xvN5rAtdrIhguHSOpBIPk2pgXn7NxX0S2pkbndNvo5OJhSDc51
uW8vzxnt80IZeFmmWW/V62AjBzY2UmEPtjptuTViY/U3Zy7p0QZyhdkc555ZUbWZcTVoqoxmQVfg
JZMbRUB0drve+xTys+0Sf6sKotD9Wu5lrfIWslRTAu69vb883+zBedot1qGvTUWgBqu8EoUbyV0s
LHNrxfkyQey5j5MWu+rXANNNe1fcU7ShjeTOKqsmhWQs0sZi1sSef0XyTeCb4y6LNo0n8XPpltiw
KOPsni1wFj4PWC01fNUZLvmt0nuYAV3adxWQ882o/CNSAWeyqT1Bg95ljpXk4/ReIpM3+As2k/zy
yXc2INDItsaILbTqyWmCcpzGR3a7cmYzcb7HEC2Dv4Z78Wkpqq5XbNeDkqSlEnlGarhkqScpCO3U
SK0XTSyMwa6OGhD+XYHQiktMFulviuKtXh9o5CsS/Hb2EnWmzN9HuO2HjRLw69nScKva/T7dUjUi
37pMtRNlh13w27zb7kB7ua855//CwRL657NbTcHfVeyE1V0JlQ24zxcWjOVwaHgj5++lyhB/587x
PiTZLKR6UZPmcsAPRnTEV06+gnvpsdUDm54JLg5JdhXh8Mx4/YbPPplKANq54epE1NhYMT7ZkCAZ
SF9eNXEevqPihjZy1pMUpHfmOoX/7aRTUpaFpS/xzf8O3VI1tshvBM/p+Vi73vVVvVUFviwuFMT4
bNTG7pEMzVHT88WRED3EKxuwbces8eFxYjqENueUpDbJYv3NU9Uu1squKc5MIKn+HOWL+Hzupd7X
1Tk+wyOl9KgQDn/Lriq+OnoXuJHKLfmWtgBO7jwCFOdcDXarx6LF1V5fDSgungP9hxrsq0/PFm/O
XnB9S1KLI7wtCq0ODN9Lqs//kehHIusu+wZDNz71O3RLbKRW6ax6qMB+1XyJWbd+fiMRCEc2OJX5
Qpt7rLoJsNswRWCZmqVQ/MHAdCNflvX84umTIg60yfTjvo/qSIb241DgFrc3aeSZZ9V1RnQn4szs
Z3KvW/+NyXYUhZM6b3ZKHDG3OJLB8fh9BW4J0BzZsJj0OyEVvmL8lu6ObCK1mj1EaXy/idupYauH
z84HErJ5MlE2z6Xee5QNZafuwNfgFtscyVApLcK+1xazI2MZnenpb/iLItv052U+1HachbOs5XyJ
hb3ZLCdrNomS4U9xr1c2pJUMRH/DsqEkPg+QfVrffg1ux+ZUQaGQ2ZUsGbx6b7Rs+DzcYltAMkTq
IcE+iTMnSYbP4hDs5qJqyK7XDXhZXK01hEqGM26OH7Ku5SykyG8YOPCDOnBW7wBQp0dWRB9b5TDK
mTZQgpaLHKlPNqSVDK7+RjftnuCWBvmNlm4WloW1hLSG1gvERQ988ayzbOhm+SjmxVFkEpiD8gKx
+U7nsPYlTJD2Nc/V8LkPnfL+gvo86reFaR2k96npVkYLbY5k6D8OFWeu08ZPiR2vT5bYg2xHHm77
RPnGas/4u2Oc2S+yyb6sFPbECbdIi+IaeyJipB6LIp094VjxOF7fwdWJXi/r0VzfUs3CJC8/wevL
20OS1X6Sb0R+ObLBb1F4W5SvISbPIb2vwZEMuabmzHWKuLMT58NvYO2qJcSdMPxM7nXlG81z74JD
t3SazWrTxh+zDKklc8Tt93wNR09D+EiJJZc9vEiCt3JGgn/E5tEO+CqAlBtbKU8Qxrc0s0Cq8hAq
uF7IyPiXr872hR8y0BK9kBf85vNDXuuFjPO/dVewR3sg8NmFJgGnCPtwsNfRLX27vWFawghscyEo
iRxMIhTdQekNeBYv4QjcSEXCQnGnC+GyIVwymDhC8bR8F5yYSdRIiVQe6/ksqUcTqzWQzJ0prliy
abzs/ps8B7KOnzRdgNJiM4j/rqIToVjl+haoBTnKUYa/ekittjXNyWUMkQxBfiPvJBWmp/ls2amW
FQ6bhbIFTAHr6t481XBpI3cfAQbvzfF/nedAskbtqdpyK7WEx6tI7HKq9OuRsUsCLTR6+ZHYZdhI
SX38hpazkR3PjeNilzV1t4ZCgTLcalv/XZYO0VIbum4jrfZVjeQ3oT0BZ13GbQ74q5vcoLVXuOy7
LXm/dRvlfyOyo9mrCpSyqUKcl5t8FWDF9jXY8fUnONUnv4gDIqnMFBsjwfuV9M+nW0poRFMhdT9p
k++TLGXfd7HJ3jQYmGPg68OMhfYuBX8tAee8dGjy9QS3j6GRX0glZb1enBAOViLypEm/1K5Y1MtS
lxAGg6kX4jGvxv8OYgsCn5szvpqu7ldMEF0z1dUrFnpjIb4uwe/T7drWokcsNJevWW+2h1tPlS4d
ugr+jhMLyrDHu5WAyHedLvr5IVYtaiOBYwb2/CKe7+O3effQAVHvGZArDiZCBMRTn3pcVuow0EwZ
7YaD+ilv0KnSidaAQu0ttvxn6ZYSGvExsy/URuG2gxnrjRo7daaIb5VYIETndMZE7H7Sx3Y9GSW+
w81HSsiOJNdJZo4HovMG7CfvXLzT6Z/ll1MReDqoKVQVf+PLqaT8Z+l2RSM7Cyk7Z/cmTddOO/Jb
aM7nRR5qnPciQu+N/E5P9HX3C9IDnKeKNDr96KhJruD1JXRLC43kSeOQDLU01xI0ls8HJ9MwToJG
0O2KfN7k+KnXEqvMYb/vlAXqBWfyOHSNyUX7E3RL3xx3IrKZgXuq7wT++fZGygxcLcDN702g9Mfo
FhPjJdoW+cKNPZw1SfXUObHD8Eh/j2M/jW4fhEYsYAZtbQKn92dzKC84xbWKfotuyfEFIpWVbvEJ
yYLJHGjqAenEz/YIaRGgXXVA5S/i3nBoW67FwmZU3AOtQt/V3l+6OzGM0kl0i4k24fqVTnRKbiNN
rc28NSB/2GuC4y0LKt1/Pd2uaCT3ggTIyVcRsuuaCFxm0BkQLQPT7Xy+z9E7iCwhM+HJ3Hf6gROF
zv359zr++pqK60rpUm0GvKZklfis0a8Y6X8Njewk5AwZ8awXWhkd+MOMqUOv3OxCpqm9CVx+YGvQ
LO1osJtSU0Az8YTjCyTTy+YXgut/G+pVDfLyWgWcBMY4XseUZ3r+t9Ht2kb2Fdeud+Is5Mt3ZCVn
mvNX4DrNveBIzH2DeXZjaiRv1cnetTjKzd3+y+ysb2jf0L6hfUP7hvYN7RvaN7RvaN/QvqF9Q/sw
NC6iWO917Vz3+BvaN7Q/B+3nz3/hcaaJxuHX7c0dav+CYOgr2TBPPxz7d5q4lH/eN8T9bDmz5Ud9
f/+rJKobOfGRJvp7/6shzrSSbiwTb2+bomEK+mZmznTt/ldR1kzZaI8MWdYSn+3IexM9ohuieteW
xbtHcbTYru6KU3m0kI3Lx58tBN19tq6L4/tfLQ3/FyNKrv0L5D/H+1vSXB6Zd+ZhhRE9bEx5+U9/
po313eYf/MzmnxdD364QcX7chV3+cdeTjQ0a18/cPxn8vx93xa1qbg35pyZvTYT2jzthK6mzUU0+
dPSFrP2UWFbMj/IFmmdycobj7110J/hFkr6n7+9G05k6NtC990VdMw1d3dy7CF9SqK6PRIewNP/j
jmYvaBI1f6f3pXiijRjk/lc+w/y447Ip7u+IUkUby4ijcunubpv6Kor9Uk1TXZRk9cvnSMVvEWRD
QXAdVmzqu/j5uhxuCd2Dls9sZOgbXTHv2qK2QcxtzJQfd/w/bH5lhpAgduJZ+sddvpDqqYZoTGbo
GUQE9/+pHnNYJnT4qZ53GIguoBdmmVRPnFkon+5+Iilc5I5yAqH3f8P4CRyG+ksZLEECfISjftxt
zIMq/3zU1fGV3JVlc2jS+GvZJEysRPJFPvsBvggVLX/3zNbFjemwZms02hqGPG5pXzvZP+66iFqG
OtPCBGvcvLOFj0x72Aiv4QT+I5yQ8n4iITCCR/FwRPGupf2fZGYKdpM563Frmrr25awlkdc4Y7pO
efjQVhSzEWXRRkRnw3aicJbxYp5aDaEZ7scdE7ZvRXNIKqWF8EdqZLobuTfbbEW1jRcbfqyoq7px
/6tjbEOVGK9uWkTzuvCP/3/IbwH99O9muaKqb+T/lOOyXO4jHEcQv4LhClczXBqt2jVuUuLyefxG
3vi/kN2utIw+c6OM5sAcl8EcmGa+vRyY3urKoR0xdx3zpbn789iJTmQlfyeZqzqzpWx8OVOZ+C30
kX+C9HnWREmVxxH0CN5dwT4NS1TRws9kLsnvI16H0M55+/90ApTzk+phs5GXaDDy5gjI/eXwa7kZ
6YhbpU8gyL9wghp8izMFf+Idnz7NyW98Ek3xz7zIEHczbfKRd2UYJa+wCk2P8xmREZPfNViqf2ZM
MwOxqW4ckES1ZiP5Q1N29eiKuiH/keG5o0LrGA3tC8Z26jpr+194k0e6JRsHzJS//h+iUtSHY8IA
AA==#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$labelPerformBackupNow = New-Object 'System.Windows.Forms.Label'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$labelLastBackupOccurredOn = New-Object 'System.Windows.Forms.Label'
	$buttonBackup = New-Object 'System.Windows.Forms.Button'
	$buttonClose = New-Object 'System.Windows.Forms.Button'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$timer1 = New-Object 'System.Windows.Forms.Timer'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$OnLoadFormEvent={
	#TODO: Initialize Form Controls here
		
			$global:count = 10
			
			<#
			if (!(Test-Path -Path "\\CoralSea-Server\Server Backup"))
			{
				New-Item -ItemType directory -Name CoralSeaTesting -Path "Server Backup"
			}
			
			#>
			try
			{
				$ErrorActionPreference = 'Stop'
				
				$WS = "CoralSea-Server"
				Test-WSMan -ComputerName CoralSea-Server
				
			}
			catch
			{
				[System.Windows.Forms.MessageBox]::Show("Unable to Communicate with $WS `n `n $result `n `n Press `'OK`' to Cancel Backup", "Backup Check", 0)
			$MainForm.Close()
			}
			
			
			
			
			
			
			
			
			
			
			
			
			try {
			
			$lastBackup = (Get-ItemProperty "\\CoralSea-Server\Server Backup").LastWriteTime
			$timespan = New-TimeSpan -Days 1
			$folders = get-childitem -path "\\CoralSea-Server\Server Backup"
			$folderTimespan = New-TimeSpan -Hours 1
			$folderExists = $false
			
			
			foreach ($folder in $folders)
			{
				
				if ((($lastBackup) - $folder.lastwritetime) -lt $folderTimespan)
				{
					
					$folderExists = $true
				}
				
				
			}
			
			
			
			
			
			
			if ((((Get-Date) - $lastBackup) -gt $timespan) -and ($folderExists))
			{
				$label1.Text = $lastBackup
				$label1.ForeColor = 'Red'
			}
			elseif ((((Get-Date) - $lastBackup) -lt $timespan) -and ($folderExists))
			{
				$label1.Text = $lastBackup
				$label1.ForeColor = 'Green'
			}
			
			else
			{
				$label1.Text = "No Backup Exists!"
				$label1.ForeColor = 'Red'
				
			}
		}
		catch
		{
			[System.Windows.Forms.MessageBox]::Show("Exception Caught! `n `n$($Error[0])", "Error", 0)
			$MainForm.Close()
		}
		
	}
	
	
	
	
	
	$timer1_Tick={
		#TODO: Place custom script here
		$button1.Text = $global:count
		
		$global:count--
		
		if ($global:count -lt 0)
		{
			
			$MainForm.Close()
		}
		
	}
	
	$buttonClose_Click={
		#TODO: Place custom script here
		$MainForm.Close()
	}
	
	$button1_Click={
		#TODO: Place custom script here
		if ($timer1.Enabled)
		{
			$timer1.Enabled = $false
		}
		else
		{
			$timer1.Enabled = $true
		}
	}
	
	$buttonBackup_Click={
		#TODO: Place custom script here
		try
		{
			$timer1.Enabled = $false
			$MainForm.Hide()
			Start-Process "$($env:ProgramFiles)\CoralSea Backup\Coral Sea Backup.exe" -WorkingDirectory "$($env:ProgramFiles)\CoralSea Backup" -Wait
			$MainForm.Close()
		}
		catch
		{
			[System.Windows.Forms.MessageBox]::Show("Exception Caught! `n `n$($Error[0])", "Error", 0)
			RETURN
			
		}
	}
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonBackup.remove_Click($buttonBackup_Click)
			$buttonClose.remove_Click($buttonClose_Click)
			$button1.remove_Click($button1_Click)
			$MainForm.remove_Load($OnLoadFormEvent)
			$timer1.remove_Tick($timer1_Tick)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($groupbox1)
	$MainForm.Controls.Add($buttonBackup)
	$MainForm.Controls.Add($buttonClose)
	$MainForm.Controls.Add($button1)
	$MainForm.ClientSize = '540, 170'
	#region Binary Data
	$MainForm.Icon = [System.Convert]::FromBase64String('
AAABAAQAEBAAAAAAIABoBAAARgAAACAgAAAAACAAqBAAAK4EAAAwMAAAAAAgAKglAABWFQAAQEAA
AAAAIAAoQgAA/joAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAD/////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////+/v7/5Orl/5+yn/96lXr/fph//6q7qv/v8+//////
///////////////////////////////////////9/f3/mq+a/y1ZLv8oVCn/KVUq/ylVKv8oVCn/
NmE3/7fGuP/+/v7////////////////////////////+/v7/l6yX/z9mQP99mH7/dJB1/ytWLP8z
XTT/e5Z7/3uWfP80XTX/vcq9////////////////////////////3+Xf/ytXLP8zXDP/+vr6/7fF
t/8nVCj/KVUp/9/l3//d4t3/JVMm/z1mPv/2+Pb//////////////////////5Splf8oVSn/L1ow
//X39f+xwLH/KFQp/ylVKv/Z4Nn/09vT/ydUKP8nVCj/vcq9//////////////////////9vjXD/
KVUq/y9ZMP/09vT/4+jj/7HCsf+ywrL/8fTx/9HZ0f8nVCj/KVUq/5qumv//////////////////
////cY5x/ylVKv8vWTD/9PX0/+Tp5P+1xLX/tcS1//H08f/R2dH/J1Qo/ylVKv+arpr/////////
/////////////5itmP8oVCn/L1ow//X39f+xwLH/KFQp/ylVKv/Z4Nn/09vT/ydUKP8nUyj/wM3B
///////////////////////k6eT/LVku/zNdNP/6+vr/t8W3/ydUKP8oVSn/4OXg/97j3v8lUyb/
Q2tD//j5+P///////////////////////v7+/6G1of8+ZT7/b4xw/2mHaf8qViv/Mlwy/26Lb/9u
i2//Nl83/8bSxv/////////////////////////////////+/v7/p7qo/zJdM/8oVCn/KVUq/ylV
Kv8oVCn/Pmc//8PPw//+/v7////////////////////////////////////////////t8e3/rLys
/4uii/+OpI//t8W3//b39v//////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////AAD//wAA
//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD/
/ygAAAAgAAAAQAAAAAEAIAAAAAAAgBAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////3+/f/w8/D/1tzW/8rSyv/M1Mz/4OXg//n6
+f/+/v7/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////v7+/+7x7v+nuaf/WXta/zRdNP8nVCj/
IFAh/yFRIv8rVyz/PGM9/3SQdP/G08b/+vv6////////////////////////////////////////
//////////////////////////////////////////////////////////z8/P+5yLn/QGlA/yJR
I/8oVCn/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KFQp/yNTJP9lhmb/4ufi////////////////
///////////////////////////////////////////////////////////////////////4+fj/
jKOM/yZVJ/8oVCn/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ydUKP84
ZDn/xM/E//7+/v//////////////////////////////////////////////////////////////
////////+/z7/4qhiv8nVCj/KVUq/ydUKP8nVCj/J1Qo/yhVKf8pVSr/KVUq/ylVKv8pVSr/J1Qo
/ydUKP8nVCj/J1Qo/yhUKf81Xzb/ytPK////////////////////////////////////////////
//////////////////////7+/v+xwbH/JVQm/ydUKP+Em4T/09vT/9Pb0//T29P/rr2u/zFbMv8p
VSr/KVUq/1F1Uf/K1Mr/09vT/9Pb0//K1Mv/S29M/ydUKP8+aT//7O/s////////////////////
////////////////////////////////////////6Ozo/zhjOf8oVCn/KVUq/z5mP//5+vn/////
//39/f93k3j/JVMm/ylVKv8pVSr/KFUp/8fQx////////////8PNw/8fUSD/KVUq/yZTJ/96l3r/
/f79//////////////////////////////////////////////////7+/v+WrJb/I1Ik/ylVKv8p
VSr/O2I8//Dy8P//////+vv6/22Jbf8nVCj/KVUq/ylVKv8pVSr/use6////////////s7+z/yRS
Jf8pVSr/KVUq/yxZLf/f5N//////////////////////////////////////////////////+/z7
/0htSf8oVSn/KVUq/ylVKv83YDj/7O/s///////5+vn/aIVo/ydUKP8pVSr/KVUq/yhVKf+zwbT/
//////////+ruqv/JVMm/ylVKv8pVSr/I1Ik/5mtmf/+/v7/////////////////////////////
///////////////h5eH/LFct/ylVKv8pVSr/KVUq/zVeNf/r7uv///////n6+f9ohWj/J1Qo/ylV
Kv8pVSr/KVUq/7LAsv///////////6W1pf8mUyf/KVUq/ylVKv8oVSn/Xn9f//7+/v//////////
/////////////////////////////////8XPxf8hUSL/KVUq/ylVKv8pVSr/NV42/+rt6v//////
+/v7/5Splf9jhWT/ZIVk/2SFZP9mhmb/ydPJ////////////pLSk/yZTJ/8pVSr/KVUq/ylVKv8/
ZUD//P38////////////////////////////////////////////tsK2/yJRI/8pVSr/KVUq/ylV
Kv81Xjb/6ezp//////////////////////////////////////////////////////+ktKT/JlMn
/ylVKv8pVSr/KVUq/zVdNv/2+Pb///////////////////////////////////////////+4w7j/
IlEj/ylVKv8pVSr/KVUq/zVeNv/p7On/////////////////////////////////////////////
/////////6S0pP8mUyf/KVUq/ylVKv8pVSr/NV01//b49v//////////////////////////////
/////////////8jRyP8hUSL/KVUq/ylVKv8pVSr/NV42/+ns6f//////+/v7/5irmP9qiWv/a4lr
/2uJa/9tiW3/ytTK////////////pLSk/yZTJ/8pVSr/KVUq/ylVKv9AZkD//P38////////////
////////////////////////////////5urm/y5YLv8pVSr/KVUq/ylVKv81XjX/6+7r///////5
+vn/aIVo/ydUKP8pVSr/KVUq/ylVKv+ywLL///////////+ltaX/JlMn/ylVKv8pVSr/KFQp/2WF
Zv/+/v7////////////////////////////////////////////8/fz/UHNR/yhUKf8pVSr/KVUq
/zdgOP/s7+z///////n6+f9ohWj/J1Qo/ylVKv8pVSr/KFUp/7PBtP///////////6u6q/8lUyb/
KVUq/ylVKv8iUSP/oLOg//7+/v////////////////////////////////////////////////+k
t6T/IlEj/ylVKv8pVSr/O2I8//Dy8P//////+vv6/22Jbf8nVCj/KVUq/ylVKv8pVSr/use6////
////////s8C0/yRSJf8pVSr/KFQp/zBeMf/l6uX/////////////////////////////////////
/////////////////+7x7v9Ca0P/KFQp/ylVKv9BaUH/+fr5///////9/f3/eZR5/yVTJv8pVSr/
KVUq/ydVKP/H0cj////////////I0cj/H1Eg/ylVKv8mUyf/jaWN//7+/v//////////////////
/////////////////////////////////////v7+/8LOwv8oVyj/J1Qo/3+Xf/+4xbn/uMW5/7jF
uf+er57/MFox/ylVKv8pVSr/TXFO/7TCtf+4xbn/uMW5/7XCtf9LbUv/J1Qo/05zT//z9fP/////
/////////////////////////////////////////////////////////////f39/52xnf8oVir/
J1Qo/yZTJ/8mUyf/JlMn/ydUKP8oVSn/KVUq/ylVKv8oVCn/JlMn/yZTJ/8mUyf/JlMn/ydUKP8+
Zz//2eDZ////////////////////////////////////////////////////////////////////
////////+/v7/6S3pP8qWSv/J1Qo/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq
/yhVKf8lUyb/R29I/9fe1//+/v7/////////////////////////////////////////////////
/////////////////////////////////////9HZ0f9UelT/I1Ik/yhUKf8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8lUib/LFgt/4Ccgf/u8e7/////////////////////////////////////////
//////////////////////////////////////////////////////////////f49//BzcH/dJB1
/0JoQ/8xWjH/LVcu/y5YL/81XTX/UHNR/5CmkP/d493//f79////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////+/v7/+/z7/+zv7P/h5uH/4+jj//P18//9/f3//v7+////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAMAAAAGAA
AAABACAAAAAAAIAlAAAAAAAAAAAAAAAAAAAAAAAA/v7+//7+/v////////////7+/v//////////
//////////////////7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7///////7+/v//////
//////7+/v////////////7+/v////////////7+/v////////////7+/v////////////7+/v//
//////////7+/v////////////7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7///////7+
/v/+/v7//v7+///////+/v7////////////+/v7//v7+///////+/v7//v7+///////+/v7/////
//7+/v///////v7+////////////////////////////////////////////////////////////
//////7+/v////////////7+/v/+/v7//v7+//7+/v/////////////////+/v7////////////+
/v7//v7+//7+/v/+/v7//////////////////////////////////////////////////v7+////
/////////v7+//7+/v////////////7+/v/+/v7////////////+/v7///////7+/v/+/v7/////
//7+/v/+/v7///////7+/v/+/v7///////7+/v////////////7+/v//////////////////////
//////7+/v////////////7+/v////////////7+/v///////v7+//7+/v///////v7+//7+/v/+
/v7////////////+/v7///////7+/v////////////7+/v////////////7+/v//////////////
///+/v7///////7+/v/+/v7///////7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
//7+/v/+/v7///////7+/v////////////7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/
//////7+/v/+/v7////////////////////////////+/v7////////////+/v7//v7+///////+
/v7//v7+///////+/v7//v7+//7+/v///////v7+/////////////v7+////////////////////
/////////v7+//////////////////7+/v////////////7+/v////////////7+/v/+/v7//v7+
///////+/v7//v7+//7+/v/+/v7//////////////////v7+//7+/v//////////////////////
/////////////////v7+///////////////////////////////////////+/v7//v7+//7+/v/+
/v7//v7+//7+/v/+/v7///////7+/v/+/v7/////////////////////////////////////////
/////////v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+///////+/v7//v7+/////////////v7+
/////////////v7+///////////////////////+/v7////////////+/v7////////////+/v7/
//////7+/v/5+fn/8/Tz/+7x7v/t8O3/7fDt//Hz8f/2+Pb//f39//7+/v////////////7+/v//
//////////7+/v////////////7+/v////////////7+/v/+/v7//v7+//7+/v/+/v7/////////
///+/v7///////7+/v////////////7+/v///////v7+///////+/v7////////////+/v7/////
//7+/v/+/v7///////7+/v//////3+Tf/7PAs/+Kn4r/aoZr/1F0Uv9KcEv/S3BM/159Xv99lX3/
oLGh/8vTy//3+Pf//v7+///////+/v7////////////+/v7///////7+/v/+/v7////////////+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7/////////////////////////////////////////
//////////////7+/v/////////////////+/v7/8vTy/7vKu/9kg2X/NF41/ylWKv8nVCj/J1Qo
/ydUKP8mUyf/JlMn/ydUKP8nVCj/J1Qo/y5aL/9HbEj/la2V/+Dm4P/9/f3///////7+/v/+/v7/
//////////////////////////////////////////////////////////////////////7+/v/+
/v7////////////////////////////////////////////+/v7///////39/f/c4dz/Y4Rj/yFT
Iv8hUSL/KFQp/ylVKv8oVSn/KVUq/ylVKv8oVCn/KVUq/ylVKv8oVCn/KVUq/ylVKv8mUyf/Gk4b
/z9qP/+puan/9ff1//7+/v/+/v7//v7+///////+/v7/////////////////////////////////
/////////////////v7+/////////////////////////////////////////////v7+///////+
/v7/9ff1/5mtmv8oWyn/I1Ek/ylVKv8oVSr/KFUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/KVUq/ydUKP8bThz/aopq/9fe1////////v7+////////////////
///////+/v7//////////////////v7+//7+/v/+/v7//v7+/////////////v7+////////////
//////7+/v////////////7+/v/v8u//jKGM/ydXKP8lUyb/KVUq/ylVKv8oVCn/KVUq/ylVKv8o
VSn/KFUp/ylUKv8oVSn/KFUp/ylUKv8oVCn/KFUp/ylVKv8oVSn/KFUp/ylVKv8oVSn/IVIi/0tw
TP/T2tP//f39//7+/v/+/v7//////////////////////////////////////////////////v7+
//7+/v/+/v7///////7+/v/+/v7///////7+/v/+/v7///////X29f+KoIr/JlQn/yhUKf8oVSn/
KFUp/yhVKf8oVSn/KFUp/yhVKf8oVSr/KVUq/ylUKv8oVSn/KVUq/ylUKv8oVSn/KFUp/yhVKf8o
VSn/KFUp/yhVKf8oVSn/KFUp/yNSJP9Lb0z/193X///////+/v7///////7+/v////////////7+
/v////////////7+/v///////v7+//7+/v/+/v7///////7+/v/////////////////+/v7/+vv6
/5ClkP8nVij/KFQp/zNdNf9Zelr/W3xb/1t8W/9bfFv/W3xb/1t8W/9ae1v/MVsy/ylVKv8oVCn/
KVUq/yJRI/9NcU7/W31c/1t8W/9bfFv/W3xb/1t8W/9cfVz/Q2hE/ylVKv8kUiX/VnhW/9/k3//+
/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//////////////////v7+////
/////////v7+//7+/v/+/v7/1dzV/yRWJP8lUyb/KFUp/zdgOP+ruqv/9Pb0//T29P/09vT/9Pb0
//L08v+ntqf/NF01/ylVKv8oVSn/KFUq/yBQIf9uim7/4OXg//T29P/09vT/9Pb0//T29P/h5eH/
W3pc/yhUKf8oVSn/IlMj/32Yff/8/Pz///////////////////////7+/v/+/v7/////////////
/////v7+//7+/v/+/v7///////7+/v/////////////////r7uv/UXhS/yVTJv8oVSn/KFUp/yFR
I/9Qc1H/+fr5//7+/v///////v7+//Hz8f9BaUL/IlIj/ylVKv8oVSr/KVUq/ylVKv8mVSf/sL6w
//7+/v/+/v7//v7+//39/f+vvK//F04Y/yhVKf8oVCn/J1Qo/x5QH//G0Mb/////////////////
//////7+/v////////////7+/v///////v7+//7+/v/+/v7//v7+//7+/v/+/v7///////////+q
vKr/HlAf/yhVKf8pVSr/KVUq/yVTJv9Mb03/7vDu//7+/v/+/v7//////+To5P9CZ0P/JlMn/ylV
Kv8pVSr/KFQp/ylVKv8pVir/oLGg//39/f/+/v7///////n5+f+aqpr/IFAh/ylUKv8oVCn/KVUq
/yNSJP9bgVv/8vTy//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v//////
/////////////////v7+//n5+f9Ock7/JFIl/ylVKv8pVSr/KVQp/yVTJv9FaUb/5+vn//7+/v//
/////v7+/93j3f87Yjz/JlMn/ylVKv8oVSr/KVUq/ylVKv8qViv/mKuY//z9/P/+/v7//v7+//j5
+P+RpJH/IlEj/ylVKv8oVSn/KFUp/ylVKv8kUSX/wczB//7+/v////////////7+/v/+/v7//v7+
//////////////////7+/v////////////7+/v///////////8jRyP8tWS7/KFUp/yhUKv8oVSn/
KFUp/yZTJ/9CZ0P/5Ojk///////+/v7//v7+/9rg2v85YDr/JlMn/ylVKv8oVCn/KFQp/ylVKv8o
VSn/kaWR//z8/P/+/v7//v7+//f59/+Jnon/I1Ik/ylVKv8oVCn/KFQp/ylVKv8dTx7/dpJ2////
///+/v7//v7+///////+/v7//v7+///////+/v7////////////+/v7//v7+//7+/v/+/v7/+/z7
/5usm/8nVCj/KVQq/yhVKf8pVCr/KVQq/yZTJ/8+ZD//4ufi//7+/v///////////9rg2v86YTr/
J1Qo/ylVKf8pVSr/KFUp/ylVKv8oVSn/j6SP//z8/P////////////b39v+EmoT/JFIl/ylUKv8o
VSn/KVUq/ylVKv8nVCj/QmlD//P08//+/v7//v7+/////////////v7+///////+/v7//v7+//7+
/v/////////////////+/v7/8/Xz/2qGa/8oVCn/KVUp/yhUKf8pVSr/KVUq/yZTJ/8+ZD7/4ebh
//7+/v///////////9rg2v86YTr/J1Qo/ylVKv8oVSn/KFUp/ylVKv8pVSr/j6SP//z8/P/+/v7/
/v7+//X39f+CmYL/JFIl/ylVKv8pVSn/KVUq/ylVKv8oVSn/L1sw/8/Wz////////v7+//7+/v/+
/v7//v7+//////////////////7+/v/+/v7//v7+///////+/v7/7O/s/0xxTf8nVCj/KVUq/ylV
Kv8oVCn/KVUq/yZTJ/8+ZD7/4OXg//7+/v///////////9vh2/9EaUX/LFos/y1bLf8tWy3/LVst
/y1bLf8xXDL/laiV//z8/P/+/v7//v7+//X39f+Al4D/JVMm/ylVKv8pVSr/KVUq/ylVKv8pVSr/
KlYr/7XBtf/+/v7//v7+///////+/v7//v7+///////+/v7///////7+/v///////v7+//7+/v//
////4ufi/0RqRP8nVCj/KVUq/yhUKv8pVCr/KVUq/ydTKP8+ZD7/3uPe///////+/v7//v7+//r7
+v/q7er/6Ozo/+js6P/o7Oj/6Ozo/+js6P/o7Oj/8vTy//7+/v///////v7+//X39f+Al4D/JVMm
/ylVKv8pVCr/KVUq/ylVKv8pVSr/KFUp/6W1pv/9/v3//v7+///////////////////////+/v7/
////////////////////////////////3OHc/z1kPv8nVCj/KVUq/ylVKv8pVSr/KFQq/ydTKP8+
ZD7/3uPe//7+/v/+/v7//v7+///////+/v7///////7+/v/+/v7//v7+//7+/v/+/v7//v7+////
///+/v7//v7+//X39f+Al4D/JVMm/ylUKv8oVSr/KVUq/ylUKv8pVSr/J1Qo/5yunP/8/fz/////
//7+/v////////////7+/v/////////////////+/v7//v7+///////+/v7/3eLd/0BnQf8nVCj/
KFQp/ylVKv8oVCn/KFQp/yZTJ/8+ZD7/3uPe///////+/v7//v7+///////+/v7//v7+////////
/////v7+/////////////v7+//7+/v///////v7+//X39f+Al4D/JVMm/ylVKf8oVSn/KFUp/ylV
Kv8pVSr/J1Qo/5yunP/8/fz//v7+/////////////v7+//////////////////7+/v//////////
///////+/v7/5urm/0RqRP8nVCj/KVUq/ylVKv8pVSr/KVQq/ydTKP8+ZD7/3uPe//7+/v/+/v7/
//////r7+v/v8u//7/Lv/+/y7//v8u//7/Lv/+/y7//v8u//9fb1//7+/v///////v7+//X39f+A
l4D/JVMm/ylVKv8pVCr/KVUq/ylVKv8pVSr/J1Uo/6W1pv/9/v3//v7+//7+/v//////////////
///+/v7/////////////////////////////////7vDu/05yT/8mVCj/KVUq/yhVKf8pVSr/KVUq
/ydTKP8+ZD7/3uTe///////+/v7//////9vh2/9HaUf/L1ow/zBbMP8wWzD/MFsw/zBbMP80WzT/
lqmW//z8/P/+/v7//v7+//X39f+Al4D/JVMm/ylVKv8oVSn/KVUq/ylVKv8pVSr/Klcr/7bCt///
///////////////////////////////////////////////+/v7//v7+///////+/v7/9Pb0/3KN
c/8nVCj/KVUq/yhUKv8pVSn/KVUq/yZTJ/8+ZD7/4ebh//7+/v/+/v7//////9rg2v86YTr/J1Qo
/ylVKv8pVSr/KVUq/ylVKv8pVSr/j6SP//z8/P///////v7+//X39f+CmYL/JFIl/ylVKv8pVCn/
KFQp/ylVKv8pVSr/MVwy/9bd1v///////v7+/////////////v7+/////////////v7+//7+/v/+
/v7///////7+/v/+/v7//f39/6S0pP8oVSn/KVUq/ylUKf8oVCn/KVUq/yZTJ/8+ZD//4ufi//7+
/v///////////9rg2v86YTr/J1Qo/ylVKv8oVCn/KVUq/ylVKv8oVSn/j6SP//z8/P//////////
//b39v+EmoT/JFIl/yhUKv8oVCn/KFQq/yhUKv8mUyf/SG1K//j6+P/+/v7//v7+//7+/v/+/v7/
/v7+//7+/v/+/v7//////////////////v7+/////////////v7+/9Pa0/8wXDH/KFQp/yhUKf8p
VSr/KVUq/yZTJ/9CZ0P/5Ojk///////+/v7//////9rg2v85YDr/JlMn/ylUKv8oVCn/KFQp/ylV
Kv8oVSn/kaWR//z8/P///////v7+//f59/+Jnon/I1Ik/ylUKv8oVSn/KFUp/ylVKv8dTR3/gpqC
///////////////////////////////////////////////////////+/v7//v7+//7+/v//////
/v7+//7+/v9ef17/IVEi/ylVKv8pVSr/KVUq/yVTJv9FaUb/5+vn//7+/v///////v7+/93j3f87
Yjz/JlMn/yhVKv8pVSr/KFQp/yhVKv8qVir/mKuY//z9/P////////////j5+P+RpJH/IlEj/ylV
Kv8oVCn/KVUq/yhVKv8lVyb/y9bL///////+/v7////////////+/v7//v7+///////+/v7//v7+
//7+/v/+/v7///////7+/v/+/v7///////////+6yrv/IVMi/ylVKv8oVSn/KFQp/yVTJv9Nb07/
7vDu//7+/v///////v7+/+To5P9CZ0P/JlMn/ylVKv8pVSr/KVUq/ylVKv8pVir/oLGg//39/f//
//////////r6+v+drZ7/IFAh/yhUKv8pVSr/KVUq/yJRIv9vj2//9/j3//7+/v/+/v7//v7+//7+
/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//////////////////v7+///////y9PL/aYhp
/yBRIv8pVSr/KVUq/yBRIP9Xelf/+fr5//////////////////L08v9FbEb/IlIj/ylVKv8oVCn/
KFQp/ylVKv8kVCb/sr+y//7+/v/+/v7///////39/f+3wrf/F04Y/yhVKf8oVSn/JlMn/ypZK//a
4Nr///////////////////////7+/v/+/v7///////7+/v/+/v7//v7+//7+/v/+/v7/////////
///////////////////+/v7/4OXg/zZhNv8lUyb/KVUq/ztjPP+yvrL/3+Tf/9/k3//f5N//3+Tf
/9/j3/+ot6n/NV42/ylUKf8pVCr/KVUq/yFRIv9xi3H/1tzW/9/k3//f5N//3+Tf/9/k3//X3df/
ZIBk/ylVKv8oVSn/JlUo/5msmv/9/f3///////7+/v////////////7+/v////////////7+/v//
//////////7+/v/+/v7//v7+//7+/v/+/v7//v7+/////////////v7+/6q7qv8pWin/KFQp/y5Z
L/9FakX/RmxG/0ZsRv9GbEb/RmxG/0ZsR/9EakX/LFgt/ylVKv8pVSr/KFQp/yZTJ/88Yzz/RmxH
/0ZsRv9GbEb/RmxG/0ZsRv9HbUj/OGA4/ylVKv8hUSL/aohq/+7x7v///////v7+////////////
/////////////////v7+///////+/v7//v7+///////+/v7///////7+/v///////v7+///////+
/v7///////r7+v+ltaX/Klgs/yhUKf8oVSn/KFUp/yhVKf8pVSr/KFUp/yhVKf8pVSr/KVUq/ylU
Kv8pVCn/KFQp/ylVKv8oVSn/KFUp/yhVKf8oVSn/KVUp/yhVKf8oVSn/KFUp/yFRIv9jgWP/5+vn
/////////////////////////////v7+//7+/v///////v7+//7+/v/+/v7//v7+//7+/v/+/v7/
//////7+/v////////////7+/v////////////7+/v/29/b/rLus/y1eLf8jUiT/KVUq/yhUKf8p
VSr/KVUq/yhUKf8pVSr/KVUq/yhUKv8pVSr/KVUq/yhUKv8pVSr/KVUq/yhUKv8pVSr/KVUq/yhU
Kv8mUyf/I1Qk/2SFZP/n6+f//v7+//7+/v////////////7+/v////////////7+/v//////////
//7+/v////////////7+/v/+/v7///////7+/v/+/v7///////7+/v/////////////////+/v7/
+/z7/7rIuv9Ibkn/GU0a/yhUKf8oVSn/KFQp/ylUKf8oVCn/KFUp/ylVKv8oVSn/KVUq/yhUKf8o
VCn/KVUq/ylVKv8pVSr/KVUq/yNSJP8iUyL/iaCK/+nt6f///////v7+/////////////v7+////
//////////////////////////////////////////////7+/v/+/v7/////////////////////
//////////////////7+/v////////////7+/v/s7+z/jKSN/zNhNP8cTR3/J1Mo/ylVKf8pVSr/
KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yhUKf8gUCH/I1Ak/1yCXf/P18///Pz8//7+/v//
//////////7+/v////////////7+/v///////////////////////v7+/////////////v7+////
///+/v7//v7+///////+/v7//v7+/////////////v7+///////+/v7//v7+///////+/v7/+/v7
/9fe1/+NpY7/RWtG/y9bMP8oVSn/JlQn/ydUKP8nVCj/J1Qo/ydUKP8nVCj/K1cr/zpjO/9ph2r/
vsm+//H08f////////////7+/v////////////7+/v/+/v7///////7+/v//////////////////
/////////////////////v7+///////+/v7///////7+/v//////////////////////////////
///////////////////////////////////+/v7/9/j3/9HY0f+suqz/kqWS/32Vff94kHj/eZF6
/4edh/+gsaD/vMe8/+vu6////////v7+//7+/v/+/v7//v7+//7+/v//////////////////////
/v7+///////+/v7//////////////////v7+///////+/v7///////7+/v/////////////////+
/v7///////7+/v////////////////////////////7+/v////////////////////////////7+
/v/+/v7/+vv6//b39v/19/X/9ff1//j5+P/8/fz//////////////////v7+///////+/v7//v7+
///////+/v7///////////////////////7+/v///////v7+////////////////////////////
/v7+//7+/v///////v7+/////////////v7+///////+/v7///////7+/v/+/v7///////7+/v//
//////////7+/v////////////7+/v/+/v7///////7+/v/+/v7////////////+/v7//v7+//7+
/v/////////////////+/v7////////////+/v7///////7+/v/+/v7/////////////////////
//////////////////7+/v///////v7+//7+/v///////v7+//7+/v////////////7+/v//////
///////////+/v7///////7+/v/+/v7///////7+/v////////////7+/v/+/v7//v7+//7+/v//
//////////7+/v/+/v7//v7+//7+/v/+/v7////////////+/v7//v7+//7+/v/+/v7//v7+////
///+/v7///////7+/v/+/v7//v7+//7+/v/+/v7///////7+/v//////////////////////////
///////+/v7////////////+/v7//v7+//7+/v////////////7+/v///////v7+///////+/v7/
/v7+///////+/v7////////////+/v7////////////+/v7/////////////////////////////
/////////////////////v7+/////////////////////////////v7+//////////////////7+
/v////////////7+/v////////////7+/v///////v7+//7+/v///////v7+///////+/v7//v7+
//7+/v/+/v7//v7+///////+/v7///////7+/v/+/v7////////////+/v7/////////////////
/v7+///////+/v7//v7+//7+/v/+/v7////////////+/v7///////////////////////7+/v//
/////////////////////////////////////v7+//7+/v///////v7+//7+/v/+/v7//v7+//7+
/v/+/v7//v7+///////+/v7///////7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+
///////////////////////+/v7///////7+/v/+/v7////////////+/v7///////7+/v/+/v7/
/////////////////v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+//7+/v/+/v7//v7+////////
///////////////+/v7//v7+///////+/v7//v7+//////////////////////////////////7+
/v///////v7+/////////////v7+///////+/v7//v7+/////////////v7+/////////////v7+
///////+/v7//v7+/////////////v7+///////+/v7//v7+///////+/v7///////7+/v/+/v7/
//////7+/v/+/v7/AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAA
AP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA
//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD/
/wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//
AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8A
AAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAA
AAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//AAAAAAAA//8AAAAAAAD//wAAAAAAAP//KAAA
AEAAAACAAAAAAQAgAAAAAAAAQgAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////3+/f/7/Pv/8PLw/9Tb
1P+4w7n/orGi/5Wllf+VpZX/laWV/56unv+zvrP/0djR/+zu7P/7/Pv//f39//7+/v//////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////9ff1/9/l3/+vvq//cYtx/0xuTf87YTz/L1kw/yBQIv8aTRv/FkwY/xZMGP8dTx7/KVUq
/zhfOP9Ia0j/ZYBm/52vnf/Y39j/8PLw////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////7+/v/z9fP/yNPI/4Wghv9DaUT/JFIl/yJRI/8iUSP/JFIl
/yZTJ/8oVCn/KVUq/ylVKv8pVSr/KFUp/yhUKf8lUib/IlEj/yJRI/8iUSP/N2A4/3GRcf+6yrr/
7fDt//3+/f//////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////d4t3/hZ2F
/zdlOP8WSxf/IlEi/yhUKf8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/
KVUq/ylVKv8pVSr/KVUq/yVTJv8VTBb/K1sr/3KQcv/I0sj/9vj2////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////P18//By8H/RnNG/yNTJP8gUCH/KFQp/ylVKv8pVSr/KVUq/ylVKv8pVSr/
KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yNSJP8i
USP/OWY6/6e2p//t8O3/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////v7+/+3w7f+brJv/LV0t/yJSIv8nVCj/
KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KFQp/yVTJv8dVR3/gZeB/+Dl4P/+/v7/////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/v7+/+Tp5P+CmoL/JVYn/yJRI/8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/JlMn/xxPHv9gf2H/09rT//z8/P//////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////+zv7P+BmYH/K1gs/yRSJf8pVSr/KFUp/yhVKf8o
VSn/KFUp/ylVKv8oVSn/KFUp/yhVKf8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yhV
Kf8oVSn/KFUp/yhVKf8oVSn/KVUq/yhVKf8oVSn/KFUp/yhVKf8lUyb/I1Ik/2aDZ//W3db//v7+
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////H08f+S
ppL/J1Yo/yRSJf8oVSn/K1Ys/yhVKf8mUyf/JlMn/yZTJ/8mUyf/JlMn/yZTJ/8nVCj/KlYr/ylV
Kv8oVSn/KVUq/ylVKv8pVSr/KVUq/ydUKP8rViz/J1Qo/yZTJ/8mUyf/JlMn/yZTJ/8mUyf/JlMn
/ydUKP8oVSn/KFUp/yZTJ/8lUyb/bYlt/+bq5v//////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////n6+f+zv7P/J1kn/yNSJf8oVSn/KFUp/2uHbP+nuKj/q7ur/6u7
q/+ru6v/q7ur/6u7q/+ru6v/q7ur/5+wn/9FakX/KFUp/ylVKv8pVSr/KVUq/ylVKv8ZTxn/m62c
/6u7rP+ru6v/q7ur/6u7q/+ru6v/q7ur/6u7q/+ru6z/fZR+/zBaMf8nVCj/JVMm/x1QHv+UppT/
9PX0////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////7+/v/Y3tj/Qm5C/yFR
Iv8pVSr/KFUp/yVTJv9DaET/usa6//v7+//7+/v/+/v7//v7+//7+/v/+/v7/+fr5/+InYj/MFsx
/yhUKf8pVSr/KVUq/ylVKv8pVSr/I1Ik/2yHbP/Y3dj/+/v7//v7+//7+/v/+/v7//v7+//7+/v/
2N7Y/1t5W/8mUyf/KFQp/ylVKv8mUyf/I1oj/8DKwP/9/f3/////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////r7uv/co9y/yJSI/8oVCn/KVUq/ylVKv8pVSr/FUsX/2iDaP/7+/v/////
//////////////////3+/f/By8H/MmAy/x9RIP8pVSr/KVUq/ylVKv8pVSr/KVUq/ydUKP8lVSf/
m62b//39/f///////////////////////Pz8/5usnP8OSw//KVUq/ylVKv8pVSr/KVUq/yJRI/9S
d1P/3eLd////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////9/f3/uMW4/ytbK/8hUSL/KVUq
/ylVKv8pVSr/KVUq/x5PH/9ee17/6+7r///////////////////////5+vn/sb6x/zlhOv8lUib/
KVUq/ylVKv8pVSr/KVUq/ylVKv8oVCn/K1cs/46ijv/19vX///////////////////////Dy8P+H
mof/G04c/ylVKv8pVSr/KVUq/ylVKv8lUyb/IVYh/5iumP/6+/r/////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////7vHu/2+Nb/8YSxn/KFUp/ylVKv8pVSr/KVUq/ylVKv8hUCL/Wnha/+Xp5f//////
////////////////9/j3/6m4qf83YDj/JlMn/ylVKv8pVSr/KVUq/ylVKv8pVSr/KFQp/ypWK/+H
nYf/8vTy///////////////////////s7+z/fpN+/x1PHv8pVSr/KVUq/ylVKv8pVSr/KVUq/x9Q
IP9NdU7/2uDa////////////////////////////////////////////////////////////////
/////////////////////////////////////////////v7+/8zVzP8vWzD/JFMl/ylVKv8pVSr/
KVUq/ylVKv8pVSr/IVAi/1FxUf/e5N7///////////////////////X29f+gsKD/M1w0/yZTJ/8p
VSr/KVUq/ylVKv8pVSr/KVUq/yhUKf8sVyz/g5mD/+7x7v//////////////////////6u7q/3aO
dv8hUSH/KVUq/ylVKv8pVSr/KVUq/ylVKv8nVCj/H0sg/6W1pf/9/f3/////////////////////
////////////////////////////////////////////////////////////////////////////
//////z9/P+LoIz/IlEj/yhVKf8pVSr/KVUq/ylVKv8pVSr/KVUq/yJRI/9Pb0//2+Db////////
///////////////09vT/na6d/zJcM/8mUyf/KVUq/ylVKv8pVSr/KVUq/ylVKv8oVCn/KVUq/32V
ff/s7+z//////////////////////+rt6v9uiG7/IVEi/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq
/xZMF/9qimr/7fDt////////////////////////////////////////////////////////////
///////////////////////////////////////////19vX/U3JT/yJRI/8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8jUST/SmxK/9rg2v//////////////////////9Pb0/52unf8zXDT/JlMn/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/KFQp/ylVKv96k3v/6u7q///////////////////////o7Oj/bIZs
/yNSJP8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8kUiX/N184/9Xc1f/+/v7/////////////////
////////////////////////////////////////////////////////////////////////////
////1dvV/z1iPv8kUiX/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/IlEj/0dqR//X3tf/////////
//////////////T29P+drp3/M1w0/yZTJ/8pVSr/KVUq/ylVKv8pVSr/KVUq/yhUKf8pVSr/epN7
/+ru6v//////////////////////5Ojk/2eDZ/8jUST/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/
KFUp/yVTJv+vva///f39////////////////////////////////////////////////////////
/////////////////////////////////////////7C9sP8pVSr/J1Qo/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/KVUq/yNRJP9Hakf/197X///////////////////////09vT/na6d/zNcNP8mUyf/KVUq
/ylVKv8pVSr/KVUq/ylVKv8oVCn/KlYr/3qTe//q7ur//////////////////////+To5P9ng2f/
I1Ek/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yhVKf8jUST/g5mE//z8/P//////////////////
////////////////////////////////////////////////////////////////////////////
//+YqJj/GU0b/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8kUiX/R2pI/9fe1///////////
////////////8/Xz/5Onk/8eTB//Cj8K/wpBCv8KQQr/CkEK/wpBCv8KQQr/CkAK/xJDEv9tiG3/
6Ozo///////////////////////k6OT/ZYFl/yRSJf8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/IlEj/2R/Zf/7/Pv/////////////////////////////////////////////////////////
///////////////////////////////////2+Pb/iJyI/xpNG/8pVSr/KVUq/ylVKv8pVSr/KVUq
/ylVKv8pVSr/JFIl/0dqR//T2tP///////////////////////v7+//f5N//ws3C/73Kvf+9yr3/
vcq9/73Kvf+9yr3/vcq9/73Kvf+/y7//1t3W//j5+P//////////////////////5Ojk/2SBZP8k
UiX/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yNRJP9Tc1T/+fr5////////////////////
////////////////////////////////////////////////////////////////////////9Pb0
/32Tff8bTRz/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yRSJf9Hakf/09rT////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////+To5P9kgWT/JFIl/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8jUST/SmtK/+7y7v//////////////////////////////////////////////////////////
//////////////////////////////////Dy8P92jXb/G00c/ylVKv8pVSr/KVUq/ylVKv8pVSr/
KVUq/ylVKv8kUiX/R2pH/9Pa0///////////////////////////////////////////////////
///////////////////////////////////////////////////////////////k6OT/ZIFk/yRS
Jf8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/I1Ek/0VoRf/u8u7/////////////////////
///////////////////////////////////////////////////////////////////////w8vD/
e5F7/xtNHP8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/JFIl/0dqR//T2tP/////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////5Ojk/2SBZP8kUiX/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq
/yNRJP9FaEX/7vLu////////////////////////////////////////////////////////////
////////////////////////////////9Pb0/3+Uf/8bTRz/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/KVUq/yRSJf9Hakf/09rT////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////+To5P9kgWT/JFIl
/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8iUSP/SmtK/+7y7v//////////////////////
//////////////////////////////////////////////////////////////////////7+/v+K
nor/Gk0b/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8kUiX/R2pH/9Pa0///////////////
////////+/v7/+Ln4v/N1s3/y9XL/8vVy//L1cv/y9XL/8vVy//L1cv/y9XL/8zVzP/c4tz/+Pn4
///////////////////////k6OT/ZIFk/yRSJf8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/
I1Ek/1NzVP/5+vn/////////////////////////////////////////////////////////////
////////////////////////////////////m6qb/xpOG/8oVSn/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/JFIl/0dqR//U29T///////////////////////P18/+Tp5P/Hkkf/wo8Cv8KPgr/Cj4K
/wo+Cv8KPgr/Cj4K/wo9Cv8SPhL/bYht/+js6P//////////////////////5Ojk/2WBZf8kUiX/
KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yJRI/9ogmj/+/z7////////////////////////
/////////////////////////////////////////////////////////////////////////7nE
uf8tWC7/JlMn/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yNRJP9Hakf/197X////////////////
///////09vT/na6d/zNcNP8mUyf/KVUq/ylVKv8pVSr/KVUq/ylVKv8oVCn/KlYr/3qTe//q7ur/
/////////////////////+To5P9ng2f/I1Ek/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8j
UST/j6SQ//z9/P//////////////////////////////////////////////////////////////
///////////////////////////////////g5eD/QGRA/yNSJP8pVSr/KVUq/ylVKv8pVSr/KVUq
/ylVKv8iUSP/R2pH/9fe1///////////////////////9Pb0/52unf8zXDT/JlMn/ylVKv8pVSr/
KVUq/ylVKv8pVSr/KFQp/ylVKv96k3v/6u7q///////////////////////k6OT/Z4Nn/yNRJP8p
VSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8nVCj/KFQp/7zJvP/+/v7/////////////////////////
////////////////////////////////////////////////////////////////////////+Pn4
/198YP8iUSP/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/I1Ek/0psSv/a4Nr/////////////////
//////T29P+drp3/M1w0/yZTJ/8pVSr/KVUq/ylVKv8pVSr/KVUq/yhUKf8pVSr/epN7/+ru6v//
////////////////////6Ozo/2yGbP8jUiT/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/IlEj/z9l
QP/b4dv//v7+////////////////////////////////////////////////////////////////
//////////////////////////////////39/f+drp3/IlEj/yhUKf8pVSr/KVUq/ylVKv8pVSr/
KVUq/yJRI/9Pb0//2+Db///////////////////////09vT/na6d/zJcM/8mUyf/KVUq/ylVKv8p
VSr/KVUq/ylVKv8oVCn/KVUq/32Vff/s7+z//////////////////////+rt6v9uiG7/IVEi/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/KFUp/xZIF/92knb/8fPx////////////////////////////////
////////////////////////////////////////////////////////////////////////////
3OPc/ztkPf8iUSP/KVUq/ylVKv8pVSr/KVUq/ylVKv8hUCL/UXFR/97k3v//////////////////
////9fb1/6CwoP8zXDT/JlMn/ylVKv8pVSr/KVUq/ylVKv8pVSr/KFQp/ytWK/+DmYP/7vHu////
///////////////////q7ur/do52/yFRIf8pVSr/KVUq/ylVKv8pVSr/KVUq/yVTJv8hUyL/sMGw
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////T29P+DnoP/FksX/yhUKf8pVSr/KVUq/ylVKv8p
VSr/IVAi/1p4Wv/l6eX///////////////////////f49/+puKn/N2A4/yZTJ/8pVSr/KVUq/ylV
Kv8pVSr/KVUq/yhUKf8qViv/h52H//L08v//////////////////////7/Hv/36Uf/8dTx7/KVUq
/ylVKv8pVSr/KVUq/yhUKf8eUB//XYNd/+bq5v//////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////yNPI/zhlOf8gUCH/KVUq/ylVKv8pVSr/KVUq/x5PH/9hfWL/6+7r////////////////////
///5+vn/sb6x/zlhOv8lUib/KVUq/ylVKv8pVSr/KVUq/ylVKv8oVCn/K1cs/46ijv/19vX/////
//////////////////L08v+Mn4z/G08d/ylVKv8pVSr/KVUq/ylVKv8lUyb/Klwq/66+rv/9/f3/
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////P18/+Mooz/JFQl/yZTJ/8pVSr/KVUq/ylV
Kv8PSg//do52//v7+////////////////////////f79/8XOxf82Yzb/H1Eg/ylVKv8pVSr/KVUq
/ylVKv8pVSr/JlMn/yNVJP+fsJ///f39///////////////////////8/Pz/p7Wn/w9LD/8oVSn/
KVUq/ylVKv8pVSr/IVEi/3CMcP/r7uv/////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///+/v7/4ebh/1t9W/8iUSL/KVUq/ylVKv8mUyf/XXtd/9LZ0v/09fT/9PX0//T19P/09fT/9PX0
//T19P/q7er/oLCg/zlhOf8oVCn/KVUq/ylVKv8pVSr/KVUq/yFSIv+Gmob/4eXh//T19P/09fT/
9PX0//T19P/09fT/9PX0/+Ln4/94j3j/KVUq/yhVKf8oVSn/IVEi/0JpQ//T2dP//v7+////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////O1c7/NmQ2/x9RIP8pVSr/J1Qo
/1FyUf99lX7/fZV9/32Vff99lX3/fZV9/32Vff99lX3/f5Z//2+KcP83Xzj/KFUp/ylVKv8pVSr/
KVUq/ylVKv8jUyT/aoVr/4CXgP99lX3/fZV9/32Vff99lX3/fZV9/32Vff+BmIL/Xnte/ytXLf8o
VSn/I1Ik/yNVJf+xv7H/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////+fr5/7G+sf8uXi7/IlEj/yhVKf8oVSn/JFIl/yNSJP8jUiT/I1Ik/yRSJf8jUiT/
I1Ik/yNSJP8mUyf/KFUp/yhVKf8pVSr/KVUq/ylVKv8pVSr/KFUp/ydUKP8jUiT/I1Ik/yNSJP8j
UiT/JFIl/yNSJP8jUiT/JFIl/yZTJ/8pVSr/JVMm/yhXKf+Jn4r/9fb1////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////19vX/n6+f/zVgNv8iUSP/
KVUq/yhVKf8oVSn/KFUp/yhVKf8pVSr/KFUp/yhVKf8oVSn/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8oVSn/KFUp/yhVKf8oVSn/KFUp/ylVKv8oVSn/KFUp/yhVKf8oVSn/I1Ik/yhX
Kf+DmoP/5+vn//7+/v//////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////v7+/+/y7/+mtqb/MmEy/x1QHv8oVCn/KVUq/ylVKv8pVSr/KVUq/ylVKv8p
VSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/IlIj/xxTHP+GnYf/5+vn//39/f//////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////+/v7/+Pn4/8DLwP9E
b0X/H1Eg/yRSJf8oVCn/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/yhVKf8lUyb/HlAf/zZiN/+ot6j/8fPx
//7+/v//////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////2+Db/3yUfP8oWij/Hk8f/yVTJv8pVSr/KVUq/ylV
Kv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq
/ydUKP8fUCD/I1gj/1+AX//EzcT/9/n3////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///u8O7/scCx/1l/Wv8lUyb/GUwa/yVTJv8pVSr/KVUq/ylVKv8pVSr/KVUq/ylVKv8pVSr/KVUq
/ylVKv8pVSr/KVUq/ylVKv8pVSr/J1Mo/xtNHP8eSh//S3RM/5yxnP/k6OT//v7+////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////z8/P/j5+P/r7+v/2qKa/80XTX/IlEj
/yJRI/8iUSP/IlEj/yRSJf8lUyb/JlMn/yZTJ/8lUyb/JFIl/yJRI/8iUSP/IlEj/y5YL/9cfl7/
obKi/9nf2f/6+/r/////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////39/f/t8O3/197X/6O0o/9yi3L/VHNU/0NnRP85Xzn/NFw1/zNbNP80XDX/
N184/z9kP/9Pb0//ZoJn/5eql//N183/6Ozo//z8/P//////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////7+/v/9/f3/
+/z7//T29P/k6OT/0NjQ/8TNxP/EzcT/xM3E/8zVzP/e5N7/8vTy//v8+//9/f3//v7+////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA==')
	#endregion
	$MainForm.MaximizeBox = $False
	$MainForm.Name = 'MainForm'
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = 'Coral Sea Backup Checker'
	$MainForm.add_Load($OnLoadFormEvent)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($labelPerformBackupNow)
	$groupbox1.Controls.Add($label1)
	$groupbox1.Controls.Add($labelLastBackupOccurredOn)
	$groupbox1.Location = '19, 17'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '503, 82'
	$groupbox1.TabIndex = 4
	$groupbox1.TabStop = $False
	#
	# labelPerformBackupNow
	#
	$labelPerformBackupNow.Font = 'Microsoft Sans Serif, 9.75pt'
	$labelPerformBackupNow.Location = '171, 56'
	$labelPerformBackupNow.Margin = '0, 0, 0, 0'
	$labelPerformBackupNow.Name = 'labelPerformBackupNow'
	$labelPerformBackupNow.Size = '160, 23'
	$labelPerformBackupNow.TabIndex = 5
	$labelPerformBackupNow.Text = 'Perform Backup Now?'
	#
	# label1
	#
	$label1.Font = 'Microsoft Sans Serif, 9.75pt, style=Bold'
	$label1.Location = '274, 29'
	$label1.Name = 'label1'
	$label1.Size = '152, 23'
	$label1.TabIndex = 4
	#
	# labelLastBackupOccurredOn
	#
	$labelLastBackupOccurredOn.Font = 'Microsoft Sans Serif, 9.75pt, style=Bold, Underline'
	$labelLastBackupOccurredOn.Location = '76, 29'
	$labelLastBackupOccurredOn.Name = 'labelLastBackupOccurredOn'
	$labelLastBackupOccurredOn.Size = '192, 23'
	$labelLastBackupOccurredOn.TabIndex = 3
	$labelLastBackupOccurredOn.Text = 'Last Backup Occurred On:'
	#
	# buttonBackup
	#
	$buttonBackup.Font = 'Microsoft Sans Serif, 9.75pt'
	$buttonBackup.Location = '121, 126'
	$buttonBackup.Name = 'buttonBackup'
	$buttonBackup.Size = '138, 30'
	$buttonBackup.TabIndex = 2
	$buttonBackup.Text = 'Backup'
	$buttonBackup.UseVisualStyleBackColor = $True
	$buttonBackup.add_Click($buttonBackup_Click)
	#
	# buttonClose
	#
	$buttonClose.Font = 'Microsoft Sans Serif, 9.75pt'
	$buttonClose.Location = '284, 126'
	$buttonClose.Name = 'buttonClose'
	$buttonClose.Size = '136, 30'
	$buttonClose.TabIndex = 1
	$buttonClose.Text = 'Close'
	$buttonClose.UseVisualStyleBackColor = $True
	$buttonClose.add_Click($buttonClose_Click)
	#
	# button1
	#
	$button1.Font = 'Microsoft Sans Serif, 9.75pt, style=Bold, Underline'
	$button1.Location = '480, 121'
	$button1.Name = 'button1'
	$button1.Size = '42, 40'
	$button1.TabIndex = 0
	$button1.UseVisualStyleBackColor = $True
	$button1.add_Click($button1_Click)
	#
	# timer1
	#
	$timer1.Enabled = $True
	$timer1.Interval = 1000
	$timer1.add_Tick($timer1_Tick)
	$groupbox1.ResumeLayout()
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	$global:count = 10
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($hostinvocation -ne $null)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
